const data = [
  {
    id: 1,
    name: "Music Club",
    mentor: "John Smith",
    img: require("../../assets/musicClub.png"),
    schedule: new Date("2023-12-05T09:00:00Z"),
    quota: 30,
    room: "Music Room A",
    onPress: "MusicClub",
  },
  {
    id: 2,
    name: "Debate Society",
    mentor: "Emily Johnson",
    img: require("../../assets/debateSociety.png"),
    schedule: new Date("2023-11-30T16:30:00Z"),
    quota: 25,
    room: "Auditorium",
    onPress: "DebateSociety",
  },
  {
    id: 3,
    name: "Art Workshop",
    mentor: "Sarah Davis",
    img: require("../../assets/artWorkshop.png"),
    schedule: new Date("2023-12-10T13:00:00Z"),
    quota: 20,
    room: "Art Studio",
    onPress: "ArtWorkshop",
  },
  {
    id: 4,
    name: "Coding Club",
    mentor: "David Brown",
    img: require("../../assets/codingClub.png"),
    schedule: new Date("2023-12-08T10:45:00Z"),
    quota: 15,
    room: "Computer Lab B",
    onPress: "CodingClub",
  },
  {
    id: 5,
    name: "Dance Team",
    mentor: "Olivia Garcia",
    img: require("../../assets/danceTeam.png"),
    schedule: new Date("2023-12-07T15:15:00Z"),
    quota: 18,
    room: "Dance Studio",
    onPress: "DanceTeam",
  },
  {
    id: 6,
    name: "Science Olympiad",
    mentor: "Michael Lee",
    img: require("../../assets/scienceOlympiad.png"),
    schedule: new Date("2023-12-09T11:30:00Z"),
    quota: 22,
    room: "Science Lab 1",
    onPress: "ScienceOlympiad",
  },
  {
    id: 7,
    name: "Photography Club",
    mentor: "Sophia Wilson",
    img: require("../../assets/photographyClub.png"),
    schedule: new Date("2023-12-11T14:00:00Z"),
    quota: 12,
    room: "Photography Studio",
    onPress: "PhotographyClub",
  },
  {
    id: 8,
    name: "Chess Club",
    mentor: "Daniel Martinez",
    img: require("../../assets/chessClub.png"),
    schedule: new Date("2023-12-06T12:20:00Z"),
    quota: 20,
    room: "Chess Room",
    onPress: "ChessClub",
  },
  {
    id: 9,
    name: "Environmental Club",
    mentor: "Ava Thompson",
    img: require("../../assets/environmentalClub.png"),
    schedule: new Date("2023-12-04T08:30:00Z"),
    quota: 25,
    room: "Environmental Lab",
    onPress: "EnvironmentalClub",
  },
  {
    id: 10,
    name: "Theater Group",
    mentor: "Ethan Adams",
    img: require("../../assets/theaterGroup.png"),
    schedule: new Date("2023-12-12T17:00:00Z"),
    quota: 28,
    room: "Theater Hall",
    onPress: "TheaterGroup",
  },
];

export default data;
